import dotenv from "dotenv-flow";
dotenv.config();

export const config = {
  OTP_EXPIRE_TIME: process.env.OTP_EXPIRE_TIME ?? "2min",
  TOKEN_EXPIRE_TIME: process.env.TOKEN_EXPIRE_TIME ?? "15min",
  JWT_EXPIRE_TIME: process.env.JWT_EXPIRE_TIME ?? "8h",
  ENCRYPTION_SECRET_KEY: process.env.ENCRYPTION_SECRET_KEY,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
  BACKOFFICE_URL: process.env.BACKOFFICE_URL,
};

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  REQUEST_TIMEOUT: 408,
  UNSUPPORTED_MEDIA_TYPE: 415,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};
